In [2]:
names = iris['target_names']
names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [18]:
iris = load_iris()
X = iris['data']
y = iris['target']
names = iris['target_names']
feature_names = iris['feature_names']

In [669]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [19]:
feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [20]:
from sklearn.cluster import KMeans
from numpy import unique
from matplotlib import pyplot
from numpy import where


In [13]:
n_clusters=3
model=KMeans(n_clusters)
model.fit(X)

NameError: name 'KMeans' is not defined

In [21]:
yhat=model.predict(X)


NameError: name 'model' is not defined

In [15]:
clusters=unique(yhat)
clusters

NameError: name 'unique' is not defined

In [10]:
size=100
f = pyplot.figure()
f.set_figwidth(20)
f.set_figheight(15)
for cluster in clusters:
  row_ix=where(yhat==cluster)
  pyplot.scatter(X[row_ix,0]+size,X[row_ix,1]+size,X[row_ix,2]+size)
pyplot.show()

NameError: name 'pyplot' is not defined

In [11]:
model.predict([[5.1, 3.5, 1.4, 0.2]])

NameError: name 'model' is not defined

In [12]:
model.predict([[5.9, 3. , 5.1, 1.8]])

NameError: name 'model' is not defined

In [678]:
model.predict([[5.6, 2.7, 4.2, 1.3]]) 

array([0], dtype=int32)

In [679]:
from sklearn.cluster import DBSCAN
model1=DBSCAN(eps=.5,min_samples=7)
yhat1=model1.fit_predict(X)

In [680]:
clusters1=unique(yhat1)
clusters1

array([-1,  0,  1])

In [16]:
size=100
f1 = pyplot.figure()
f1.set_figwidth(20)
f1.set_figheight(15)
for cluster1 in clusters1:
  row_ix=where(yhat1==cluster1)
  pyplot.scatter(X[row_ix,0]+size,X[row_ix,1]+size,X[row_ix,2]+size)
pyplot.show()

NameError: name 'pyplot' is not defined